module NotificationHelper
    def send_notification(tokens,title,message)
        fcm_server_key = 'AAAAbd3aiYM:APA91bGy3mAq54D48M7GXGnE_mXlDwS2cc_TschUVzy2ULHKrEBKbYstEg7mVjosyCa8FOIyzDusqQNOJteX-Cf0Nykeqa5rSup96HgvuPX71LvvojykcM1_5ylPlrMGkVwLt3BrIoYJ'
  
        fcm = FCM.new(fcm_server_key) 
        
        registration_ids = tokens # Array of keys generated by firebase for devices 
            
        options = {
                    priority: 10,
                    notification: {
                            title: title, 
                            body: message,
                            icon: "myicon"
                    }
        }   
         
        response = fcm.send(registration_ids, options)
  
        return response    
        # if(response)
        #     return true
        # else 
        #     return false
        # end
  
                
     end
    
end
    
  